/*
** Created by Christian Howard on 3/14/24.
*/
#ifndef KRYSTALBALL_SRC_SIM_COMPILE_TIME_DISCRETE_MODEL_CRTP_BASE_H_
#define KRYSTALBALL_SRC_SIM_COMPILE_TIME_DISCRETE_MODEL_CRTP_BASE_H_

#endif //KRYSTALBALL_SRC_SIM_COMPILE_TIME_DISCRETE_MODEL_CRTP_BASE_H_
